/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as DevRouteImport } from './routes/dev'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelModelIdRouteImport } from './routes/model/$modelId'

const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelModelIdRoute = ModelModelIdRouteImport.update({
  id: '/model/$modelId',
  path: '/model/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/receipts': typeof ReceiptsRoute
  '/model/$modelId': typeof ModelModelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/receipts': typeof ReceiptsRoute
  '/model/$modelId': typeof ModelModelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/receipts': typeof ReceiptsRoute
  '/model/$modelId': typeof ModelModelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev' | '/receipts' | '/model/$modelId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev' | '/receipts' | '/model/$modelId'
  id: '__root__' | '/' | '/dev' | '/receipts' | '/model/$modelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevRoute: typeof DevRoute
  ReceiptsRoute: typeof ReceiptsRoute
  ModelModelIdRoute: typeof ModelModelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model/$modelId': {
      id: '/model/$modelId'
      path: '/model/$modelId'
      fullPath: '/model/$modelId'
      preLoaderRoute: typeof ModelModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevRoute: DevRoute,
  ReceiptsRoute: ReceiptsRoute,
  ModelModelIdRoute: ModelModelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
